a = int(input("Enter First Number: "))
b = int(input("Enter Second Number: "))
print("Addition of two numbers is: ", a + b)
print("Subtraction of two numbers is: ", a - b)
print("Multiplication of two numbers is: ", a * b)
print("Division of two numbers is: ", a / b)
print("Modulus of two numbers is: ", a % b)